volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/scraeyme/data/mariadb
      o: bind
      type: none
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/scraeyme/data/wordpress
      o: bind
      type: none

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    ports:
      - "443:443"
    env_file:
      - .env
    restart: on-failure
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    restart: on-failure
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    env_file:
      - .env
    restart: on-failure

networks:
  inception:
    name: inception
    driver: bridge
    